export const OrderByEnums = [
  // { value: '', label: 'Default'},
  { value: 'mal_id', label: 'MAL ID'},
  { value: 'title', label: 'Title'},
  { value: 'type', label: 'Type'},
  { value: 'rating', label: 'Rating'},
  { value: 'start_date', label: 'Start Date'},
  { value: 'end_date', label: 'End Date'},
  { value: 'episodes', label: 'Episodes'},
  { value: 'score', label: 'Score'},
  { value: 'scored_by', label: 'Scored by'},
  { value: 'rank', label: 'Rank'},
  { value: 'popularity', label: 'Popularity'},
  { value: 'members', label: 'Members'},
  { value: 'favorites', label: 'Favorites'},
];

export const SortEnums = [
  // { value: '', label: 'Default'},
  { value: 'asc', label: 'Ascending'},
  { value: 'desc', label: 'Descending'},
];

export const GenresEnums = [
  { value: 1, label: "Action" },
  { value: 2, label: "Adventure" },
  { value: 5, label: "Avant Garde" },
  { value: 46, label: "Award Winning" },
  { value: 28, label: "Boys Love" },
  { value: 4, label: "Comedy" },
  { value: 8, label: "Drama" },
  { value: 10, label: "Fantasy" },
  { value: 26, label: "Girls Love" },
  { value: 47, label: "Gourmet" },
  { value: 14, label: "Horror" },
  { value: 7, label: "Mystery" },
  { value: 22, label: "Romance" },
  { value: 24, label: "Sci-Fi" },
  { value: 36, label: "Slice of Life" },
  { value: 30, label: "Sports" },
  { value: 37, label: "Supernatural" },
  { value: 41, label: "Suspense" },
  { value: 9, label: "Ecchi" },
  { value: 49, label: "Erotica" },
  { value: 12, label: "Hentai" },
  { value: 50, label: "Adult Cast" },
  { value: 51, label: "Anthropomorphic" },
  { value: 52, label: "CGDCT" },
  { value: 53, label: "Childcare" },
  { value: 54, label: "Combat Sports" },
  { value: 81, label: "Crossdressing" },
  { value: 55, label: "Delinquents" },
  { value: 39, label: "Detective" },
  { value: 56, label: "Educational" },
  { value: 57, label: "Gag Humor" },
  { value: 58, label: "Gore" },
  { value: 35, label: "Harem" },
  { value: 59, label: "High Stakes Game" },
  { value: 13, label: "Historical" },
  { value: 60, label: "Idols (Female)" },
  { value: 61, label: "Idols (Male)" },
  { value: 62, label: "Isekai" },
  { value: 63, label: "Iyashikei" },
  { value: 64, label: "Love Polygon" },
  { value: 65, label: "Magical Sex Shift" },
  { value: 66, label: "Mahou Shoujo" },
  { value: 17, label: "Martial Arts" },
  { value: 18, label: "Mecha" },
  { value: 67, label: "Medical" },
  { value: 38, label: "Military" },
  { value: 19, label: "Music" },
  { value: 6, label: "Mythology" },
  { value: 68, label: "Organized Crime" },
  { value: 69, label: "Otaku Culture" },
  { value: 20, label: "Parody" },
  { value: 70, label: "Performing Arts" },
  { value: 71, label: "Pets" },
  { value: 40, label: "Psychological" },
  { value: 3, label: "Racing" },
  { value: 72, label: "Reincarnation" },
  { value: 73, label: "Reverse Harem" },
  { value: 74, label: "Romantic Subtext" },
  { value: 21, label: "Samurai" },
  { value: 23, label: "School" },
  { value: 75, label: "Showbiz" },
  { value: 29, label: "Space" },
  { value: 11, label: "Strategy Game" },
  { value: 31, label: "Super Power" },
  { value: 76, label: "Survival" },
  { value: 77, label: "Team Sports" },
  { value: 78, label: "Time Travel" },
  { value: 32, label: "Vampire" },
  { value: 79, label: "Video Game" },
  { value: 80, label: "Visual Arts" },
  { value: 48, label: "Workplace" },
  { value: 43, label: "Josei" },
  { value: 15, label: "Kids" },
  { value: 42, label: "Seinen" },
  { value: 25, label: "Shoujo" },
  { value: 27, label: "Shounen" },
];

export const StatusEnums = [
  // { value: '', label: 'Any'},
  { value: 'airing', label: 'Airing'},
  { value: 'complete', label: 'Complete'},
  { value: 'upcoming', label: 'Upcoming'},
];

export const RatingEnums = [
  // { value: '', label: 'Any'},
  { value: 'g', label: 'G - All Ages'},
  { value: 'pg', label: 'PG - Children'},
  { value: 'pg13', label: 'PG-13 - Teens 13 or older'},
  { value: 'r17', label: 'R - 17+ (violence & profanity)'},
  { value: 'r', label: 'R+ - Mild Nudity'},
  { value: 'rx', label: 'Rx - Hentai'},
];

export const TypeEnums = [
  // { value: '', label: 'Any' },
  { value: 'tv', label: 'TV' },
  { value: 'movie', label: 'Movie' },
  { value: 'ova', label: 'OVA' },
  { value: 'special', label: 'Special' },
  { value: 'ona', label: 'ONA' },
  { value: 'music', label: 'Music' },
];